### ISSUE TITLE
Generare lista IDP dinamicamente

### ISSUE THREAD

**Issue by alexrj** [italia/spid-smart-button#1]
Il codice dello Smart Button dovrebbe interrogare il Federation Registry di spid.gov.it per ottenere dinamicamente la lista degli IDP con i relativi loghi.

Questa implementazione non è possibile fino a che non è stata definita la struttura del Registry e pubblicata la relativa API (analogamente è in corso la definizione di un meccanismo dinamico di distribuzione dei metadati degli Identity Provider).

**Comment by srescio** [comment]
un'ipotesi di fetch della lista via ajax:
json mock: https://github.com/srescio/spid-smart-button/blob/issue-2/separate-html-js/src/data/spidProviders.json
https://github.com/srescio/spid-smart-button/blob/issue-2/separate-html-js/src/js/agid-spid-enter.js#L258-L281

**Comment by alexrj** [comment]
Chiudo questa issue perché è stato scelto di includere la lista degli IdP direttamente nello script pacchettizzato e distribuito via CDN, senza interrogazioni al registro.
