### ISSUE TITLE
Piano di rilascio dei vari loghi sotto licenza di contenuto libero?

### ISSUE THREAD

**Issue by valerio-bozzolan** [italia/spid-smart-button#11]
https://github.com/italia/spid-sp-access-button/issues/5

**Comment by umbros** [comment]
Non ci sono problemi di licenza d'uso sui loghi utilizzati

**Comment by valerio-bozzolan** [comment]
Come scritto, in un repository GNU GPL non vi potrebbe essere materiale non compatibile con la GNU GPL.

I plugin SPID per vari CMS saranno sotto GNU GPL: sorge il problemino.
