### ISSUE TITLE
Supporto multilingua

### ISSUE THREAD

**Issue by alexrj** [italia/spid-smart-button#16]
Il bottone deve essere visualizzabile in italiano, inglese, tedesco, attraverso un parametro `lang` da passare al metodo di inizializzazione, con fallback sull'italiano.

**Comment by simevo** [comment]
A mio parere in prima battuta avrebbe senso supportare tutte [le lingue legalmente usate nel paese](https://it.wikipedia.org/wiki/Bilinguismo_amministrativo_in_Italia), a patto che siano effettivamente usate sui siti web istituzionali .

Usando questo criterio la lista inziale di tre lingue si arricchisce del francese che trovo almeno qui:
http://www.regione.vda.it/default_f.asp
mentre risulterebbero escluse ladino, sloveno e sardo visto che da una rapida analisi nessuno si è preso la briga di localizzare alcun sito istituzionale in queste lingue.
