### ISSUE TITLE
Supporto IE

### ISSUE THREAD

**Issue by ZorbaDimatteo** [italia/spid-smart-button#20]
E' necessario fornire il supporto anche per Internet Explorer preferibilmente dalla versione 10+, ma andrebbe bene anche la versione 11, in merito alle linee guida espresse [qui](http://design-italia.readthedocs.io/it/stable/doc/user-interface/sviluppo-web.html#supporto-browser)

**Comment by francescozaia** [comment]
Ti confermo che è sufficiente il supporto per la versione 11 di Internet Explorer.
