### ISSUE TITLE
Predisporre lo Smart Button in modo che sia integrabile remotamente (hosted)

### ISSUE THREAD

**Issue by alexrj** [italia/spid-smart-button#3]
Lo scopo è quello di evitare il download dello Smart Button, lasciandolo su un server ufficiale (magari servito da una VPN), come avviene ad esempio per Facebook Login.

Per poter fare questo serve un refactoring del file di configurazione, che potrebbe essere integrato direttamente nel codice principale in modo da avere un unico file. Tuttavia gli URL degli IdP devono essere personalizzabili dall'implementazione, perché ogni SP ha una sua architettura. Una ipotesi è quella di fornire un callback con cui l'applicazione chiamante possa formattare l'URL:

```js
$(function () {
    SPID.init({
        selector: '.my-spid-button',
        url: function (idp) {
            return '/Login?entityId=' + idp.entityId;
        }
   });
});
```

Per usare il bottone in modalità POST (v. #4) si dovrebbero rendere personalizzabili il nome e il valore del campo inviato dal form quando si preme il bottone:

```js
$(function () {
    SPID.init({
        selector: '.my-spid-button',
        action: '/Login',
        fieldName: 'entityId',
        fieldValue: function (idp) {
            return idp.entityId;
        }
   });
});
```

**Comment by srescio** [comment]
bisogna tenere a mente che a parità di <input type=hidden> è il browser che si occupa di fare l'url encoding per poi chiamare la action url con i parametri adeguatamente formattati o usarli come payload in base al method get/post, senza bisogno di preparare una url diversa per i due casi, requisito gestito nella pr riferita all'issue2: https://github.com/srescio/spid-smart-button/blob/issue-2/separate-html-js/src/js/agid-spid-enter-tpl.js#L75-L86

**Comment by alexrj** [comment]
Mi immagino una cosa del genere:

```
<script src="https://cdn.spid.gov.it/smartbutton.min.js" />
```

e poi la chiamata di cui sopra

**Comment by ZorbaDimatteo** [comment]
Un'idea di config potrebbe essere questa:
in caso di GET:
````
window.agidSpidEnter.init({
    language: 'en',
    providers: {
        get: function (entityId) {
           return ‘/Login?entityId=’ + entityId;
        }
});
````

in caso di post
````
window.agidSpidEnter.init({
    language: 'en',
    providers: {
          post: function (entityId) {
                 return {
                     action: “/login”,
                     data: {
                         providerID: entityID
                      }
              }
          }
});
````
Dove le coppie chiave-valore presenti in **data** si trasformeranno in input hidden.


Infine, se si volessero fornire metodi diversi per provider:
````
window.agidSpidEnter.init({
    language: 'en',
    providers: {
        get: function (entityId) {
           return ‘/Login?entityId=’ + entityId;
        }
        poste: {
            post: function (entityId) {
                    return {
                        action: “/login”,
                        data: {
                            providerID: entityID
                        }
                }
            }
        }
});
````
dove **get** è il metodo di default per tutti i providers mentre ad esempio per Poste si può specificare una **post**.

**Comment by ZorbaDimatteo** [comment]
In ottica di rendere l'utilizzo dello spid-smart-button più semplice, abbiamo ripensato a una configurazione più snella e più simile a quella all'inizio di questa issue:
per la **get**
````javascript
var spid = new window.SPID();
spid.init({
   language: 'en',
   providers: {
       get: '/login?entityId={{entityID}}',
   }
});
````
dove il valore del parametro tra parentesi graffe verrà sostituito dalla libreria con il valore dell'**entityID** del provider corrente.

per la **post**
````javascript
var spid = new window.SPID();
spid.init({
   language: 'en',
   providers: {
      post: {
          action: '/login',
          fieldName: 'entityID'
      }
   }
});
````
dove fieldName rappresenta il nome della input nascosta contenente l'id del provider, ad es:

````html
<form id="agid-spid-provider-poste" action="/login" method="POST">
    <button type="submit"></button>
    <input name="entityID" value="https://posteid.poste.it" type="hidden">
</form>
````

e per una customizzazion per singolo provider:

````javascript
 var spid = new window.SPID();
spid.init({
   language: 'en',
   providers: {
      get: '/login?entityId={{entityID}}',
      poste: {
         post: {
            action: '/login',
            fieldName: 'entityID'
         }
     }
   }
});
````

**Comment by alexrj** [comment]
Proposta discussa di persona:

```js
SPID.init({
     selector: '.my-spid-button',  // opzionale
     method: 'GET',                // opzionale
     url: '/Login?entityId={{idp}}',
     mapping: {                    // opzionale
         'https://www.poste.it/xxx': 4,
         'https://sielteid.it/xxx': 5,
         'https://spid-testenv/sd': 7,
     }
});

SPID.init({
     selector: '.my-spid-button',  // opzionale
     method: 'POST',               // opzionale
     url: '/Login',
     fieldName: 'idp',
     extraFields: {                // opzionale
        foo: 'bar',
        baz: 'baz'
     },
     mapping: {                    // opzionale
         'https://www.poste.it/xxx': 4,
         'https://sielteid.it/xxx': 5,
         'https://spid-testenv/sd': 7,
     }
});
```

**Comment by ZorbaDimatteo** [comment]
Vengono aggiunti anche i seguenti parametri:

```javascript
extraProviders: [
   {
      "protocols": ["SAML"],
      "entityName": "Ciccio ID",
      "logo": "spid-idp-aruba.svg",
      "entityID": "https://loginciccio.it",
      "active": true
   },
   {
       "protocols": ["SAML"],
       "entityName": "Pippocert ",
       "logo": "spid-idp-infocertid.svg",
       "entityID": "https://identity.pippocert.it",
       "active": true
   }
],
supported: [
    'poste.it'
 ]
```

per indicare rispettivamente le configurazioni di provider extra che i SP potranno aggiungere e per far indicare ai SP quali provider sono supportati dal loro applicativo.
