### ISSUE TITLE
Versionamento

### ISSUE THREAD

**Issue by giuseppe-santoro** [italia/spid-smart-button#30]
Eliminare la gestione della [versione](https://github.com/italia/spid-smart-button/blob/master/src/js/agid-spid-enter.js#L15) dal codice applicativo. Verrà gestita direttamente tramite la CDN.

**Comment by alexrj** [comment]
Riapro perché mi risulta che in `dist/` vengano ancora generati due file:

* `agid-spid-enter.min.latest.js`
* `agid-spid-enter.min.1.0.0.js`

Deve essercene solo uno, chiamato `spid-button.min.js`.

**Comment by ZorbaDimatteo** [comment]
Ok pensavo di accorpare questi cambiamenti nella risoluzione di questa [issue](https://github.com/italia/spid-smart-button/issues/33)
