### ISSUE TITLE
Revisione README.md

### ISSUE THREAD

**Issue by giuseppe-santoro** [italia/spid-smart-button#31]
Il file README.md dovrebbe contenere esclusivamente informazioni utili all'utilizzatore della libreria e non allo sviluppatore. Quindi è necessario spostare nel file README-DEV.md tutta la parte in cui si spiega come contribuire al progetto.

Nel file README.md invece deve esserci:
- spiegazione di cosa è il progetto
- come integrare il pulsante in una applicazione
- elenco delle possibili configurazioni
- come compilare per generare il file minificato

**Comment by ZorbaDimatteo** [comment]
Non credo che nel readme per l'utente finale vadano le informazioni sul file minificato e la sua generazione, poiche' spid-smart-button sara' ospitato su cdn
