### ISSUE TITLE
Supportare chiamata POST

### ISSUE THREAD

**Issue by alexrj** [italia/spid-smart-button#4]
Il [bottone esistente](https://github.com/italia/spid-sp-access-button) supporta sia GET sia POST. Nel caso di GET si tratta solo di inserire gli URL; nel caso di POST è lasciato all'applicazione il compito di inserire il codice fornito all'interno di un tag `<form>` dettagliato secondo le esigenze.

Per lo Smart Button si può seguire la stessa strada, ferma restando l'architettura descritta in #3).

**Comment by srescio** [comment]
gestito nel refactoring della PR riferita all'issue2,
https://github.com/srescio/spid-smart-button/blob/73689c4b4171243926e94e9d1908474d85698d2a/src/js/agid-spid-enter-tpl.js#L91
