### ISSUE TITLE
Correzioni grafiche all'elenco degli IdP

### ISSUE THREAD

**Issue by alexrj** [italia/spid-smart-button#40]
Alcune correzioni grafiche da apportare alla schermata di selezione dell'IdP:

* dietro i singoli loghi vanno posizionati dei box grigi #f5f6f7 con angoli arrotondati (raggio 3px)
* i loghi vanno posizionati nei box senza padding (lo mettiamo direttamente nelle immagini SVG)
* il pulsante in basso deve avere label "Annulla", non "Annulla l'accesso", e deve avere lo stile del [bottone "Secondary outline" di Bootstrap Italia](https://italia.github.io/bootstrap-italia/docs/componenti/bottoni/#varianti-di-colore), e dev'essere largo fino al margine esterno dei box grigi dei loghi
* manca la manina sul tasto "Annulla" (`cursor: pointer`)
* i loghi disabilitati devono essere molto più sbiaditi
* aggiungere spazio tra "Non hai SPID?" e "Scopri di più."
* "Scopri di più." deve avere il punto, non dev'essere sottolineato e dev'essere grassetto, colore #0066cc
* "Scopri di più" al momento scompare stringendo la finestra e non è leggibile perché manca lo scroll
* in versione mobile, Annulla deve rimanere fisso mentre deve scrollare tutto il resto
* in versione tablet invece dev'essere tutto scrollabile come per desktop
* l'ombra sopra il bottone "Annulla" deve essere circolare, implementata come quella [qui presente](https://italia.github.io/bootstrap-italia/docs/componenti/tab/) (ovviamente girata al contrario)
* verificare su iPhone o telefoni stretti se il testo "Scegli il tuo provider SPID" viene tagliato orizzontalmente (può ridursi oppure andare su due righe)

Questi sono i loghi degli IdP, con dimensioni omogenee e margini inclusi: 
[Loghi IdP.zip](https://github.com/italia/spid-smart-button/files/2228729/Loghi.IdP.zip)

Questo il mockup finale:
![mobile - seleziona idp](https://user-images.githubusercontent.com/594957/43214554-e3677c8e-9039-11e8-9111-9c1151706f79.png)

**Comment by ZorbaDimatteo** [comment]
@alexrj Per problemi di compatibilita' tra browser (IE 11 non supporta la proprieta' css `filter` che viene usata per rendere grigi i bottoni disabilitati nella lista dei providers)
volevo proporre di sbiadirli e renderli opachi tramite la proprieta' `opacity` ottenendo questo risultato:
![immagine](https://user-images.githubusercontent.com/18332250/45212664-bfa60580-b295-11e8-8f7f-7fcf5b7adcb6.png)

Puo' andare bene?
