### ISSUE TITLE
Rimuovere dipendenza da repository esterno

### ISSUE THREAD

**Issue by alexrj** [italia/spid-smart-button#43]
Nel codice sono presenti vari riferimenti ai repository di @srescio:

* `github.com/srescio/grunt-serve`
* `github.com/srescio/spid-smart-button`

Dovremmo eliminarli per rendere questo repository autonomo.

**Comment by alexrj** [comment]
Risolto

**Comment by srescio** [comment]
Una nota per quanto riguarda grunt-serve, il branch che avevo fatto serviva per fixare/silenziare un security warning, l'autore ha recentemente mergiato la mia PR nel suo progetto https://github.com/lud2k/grunt-serve/pull/15, appena sarà disponibile la versione nuova 1.7 anche su npm sarà opportuno fare il bump
