### ISSUE TITLE
Refactoring codice duplicato in generazione pulsanti

### ISSUE THREAD

**Issue by dpaleino** [italia/spid-smart-button#5]
Il codice per la generazione dei pulsanti delle diverse misure è inutilmente duplicato.

**Comment by srescio** [comment]
presente anche nel refactoring riferito all'issue2 https://github.com/srescio/spid-smart-button/blob/issue-2/separate-html-js/src/js/agid-spid-enter-tpl.js#L104-L114

**Comment by srescio** [comment]
@alexrj essendo afferente al master precedente penso si possa chiudere la issue
