### ISSUE TITLE
Codice superfluo

### ISSUE THREAD

**Issue by alexrj** [italia/spid-smart-button#56]
https://github.com/italia/spid-smart-button/blob/012bc5e2693674abe47e75a14ad69a50ea0ff552/src/js/agid-spid-enter.js#L50-L68

Non abbiamo nessuna info modal. L'unica modale che si apre è quella per la scelta dei provider.

https://github.com/italia/spid-smart-button/blob/012bc5e2693674abe47e75a14ad69a50ea0ff552/src/js/agid-spid-enter.js#L70-L76

Funzione non più necessaria.

https://github.com/italia/spid-smart-button/blob/012bc5e2693674abe47e75a14ad69a50ea0ff552/src/js/agid-spid-enter-tpl.js#L22-L30

Non abbiamo immagini PNG e il bottone non è pensato per browser così vecchi da non supportare SVG.

https://github.com/italia/spid-smart-button/blob/012bc5e2693674abe47e75a14ad69a50ea0ff552/src/js/agid-spid-enter-tpl.js#L169-L175

Questo testo non serve perché non appare da nessuna parte.

**Comment by ZorbaDimatteo** [comment]
@alexrj leggo che non dovrebbe esistere nessuna infomodal. 
La infomodal esistente e' ancorata al bottone 'Non hai spid? Scopri di piu ' nella pagina della scelta del provider. 
Questo bottone continuera' ad esistere? Se si, dove deve puntare?
![immagine](https://user-images.githubusercontent.com/18332250/44797406-6e1fbb80-abaf-11e8-874a-33eb32e8390d.png)
