### ISSUE TITLE
after building, the logos for Namirial ID, SPIDItalia Register.it and Intesa ID are missing

### ISSUE THREAD

**Issue by simevo** [italia/spid-smart-button#67]
we built the project with:
```
 yarnpkg install
./node_modules/grunt-cli/bin/grunt build:prod
```
after that:
```
ls dist/img/idp-logos/ -1
spid-idp-aruba.svg
spid-idp-dummy.svg
spid-idp-infocertid.svg
spid-idp-posteid.svg
spid-idp-sielteid.svg
spid-idp-timid.svg
```

**Comment by snack-eater** [comment]
Hi, the missing logos for Namirial ID, SPIDItalia Register.it and Intesa ID are included in a commit of [this pull request](https://github.com/italia/spid-smart-button/pull/59) that must be merged to this repo ([Commit the logos](https://github.com/italia/spid-smart-button/pull/59/commits/7aa4d54e939946bbbeff4237cf2159483349a40d))
